version: "3.9"

services:
  ecoles:
    image: ghcr.io/a5hura666/ecoles-ranking:latest

    container_name: ecoles

    restart: unless-stopped

    expose:
      - "3000"

    environment:
      NODE_ENV: production
      NEXT_PUBLIC_APP_URL: https://ecoles.ethandevfs.cloud

    networks:
      - npm

networks:
  npm:
    external: true